name: Trigger auto deployment for container-app-s2hczxx7dd2ly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-s2hczxx7dd2ly-AutoDeployTrigger-ce2c2666-a928-4349-b8f3-9a61f835eb8d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPS2HCZXX7DD2LY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPS2HCZXX7DD2LY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPS2HCZXX7DD2LY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrys2hczxx7dd2ly.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPS2HCZXX7DD2LY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPS2HCZXX7DD2LY_REGISTRY_PASSWORD }}
          containerAppName: container-app-s2hczxx7dd2ly
          resourceGroup: reactbasicb535a21e
          imageToBuild: containerregistrys2hczxx7dd2ly.azurecr.io/container-app-s2hczxx7dd2ly:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


